### ISSUE TITLE
Proxy Validation

### ISSUE THREAD

**Issue by Tyluur** [KaiBurton/free-proxies-autoupdated#1]
I noticed you included this in the README:

> Free list of tested SOCKS & HTTP proxies in json & txt format. These proxies are tested 4x/day (every 6 hours) and have made a successful socket connection, and can write & read data.

How do you validate that these proxies are functional?

**Comment by KaiBurton** [comment]
@Tyluur A socket is opened and 2 bytes are sent to the destination test server (within another data centre). The test server then responds back with a stream of data, if the data is valid then the proxy is verified. This tests that both receiving and sending data works fine at the time of testing.

HTTP/HTTPS uses **CONNECT** to verify, but it's the same thing. Socket is opened and 2 bytes are sent, if the correct data is received back then the proxy is valid.

Over 100K+ public proxies are tested every 6 hours and only about ~15k-20k are valid. I will make a separate list for Web Specific Proxies, but these are guaranteed to work on Game Clients & Web Connections at the time they are tested.

[ProxyTester](https://github.com/KaiBurton/ProxyBuilder/blob/main/src/main/kotlin/spb/net/proxy/ProxyTester.kt) is what I use to test them.
